from __future__ import annotations

import json
import re
import subprocess
import sys
from typing import Any

from wb_config import resolve_openai_api_key


def _fallback_blueprint(prompt: str, project_type: str, deploy_target: str) -> dict[str, Any]:
    words = [word for word in re.findall(r"[A-Za-z0-9]+", prompt) if len(word) > 2]
    title_words = words[:3] or ["Shipstack", "Project"]
    site_name = " ".join(word.capitalize() for word in title_words)
    noun = title_words[0].capitalize()
    auth_required = any(token in prompt.lower() for token in ("auth", "login", "user", "account"))
    features = [
        {
            "title": f"{noun} dashboard",
            "description": "A clean workspace for your core workflow and project insights.",
        },
        {
            "title": "Automation-ready APIs",
            "description": "Generated endpoints that support common create, read, update, and delete flows.",
        },
        {
            "title": "Deployable project structure",
            "description": f"Prepared for {deploy_target} with environment variable templates and deployment metadata.",
        },
    ]
    entities = [
        {
            "name": "projects",
            "columns": ["id uuid primary key", "name text", "status text", "created_at timestamptz"],
        },
        {
            "name": "tasks",
            "columns": ["id uuid primary key", "project_id uuid", "title text", "completed boolean"],
        },
    ]
    return {
        "site_name": site_name,
        "summary": prompt.strip(),
        "title": f"{site_name} built for modern teams",
        "subtitle": "Generated by Shipstack with deployment-ready frontend, API, and hosting configuration.",
        "cta_text": "Launch the app",
        "project_type": project_type,
        "deploy_target": deploy_target,
        "auth_required": auth_required,
        "features": features,
        "entities": entities,
        "api_routes": [
            {"method": "GET", "path": "/api/health", "summary": "Health check"},
            {"method": "GET", "path": "/api/items", "summary": "List primary records"},
            {"method": "POST", "path": "/api/items", "summary": "Create a primary record"},
        ],
        "primary_color": "#3498db",
        "gradient_start": "#1f2937",
        "gradient_end": "#2563eb",
        "use_supabase": project_type == "fullstack_app" or deploy_target == "supabase",
    }


def _ensure_openai_module():
    try:
        from openai import OpenAI  # type: ignore
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", "openai"])
        from openai import OpenAI  # type: ignore
    return OpenAI


def generate_project_blueprint(prompt: str, project_type: str, deploy_target: str) -> dict[str, Any]:
    api_key = resolve_openai_api_key()
    if not api_key:
        return _fallback_blueprint(prompt, project_type, deploy_target)

    OpenAI = _ensure_openai_module()
    client = OpenAI(api_key=api_key)
    system_prompt = """
You design deployable software projects from natural language requests.

Return JSON only with this shape:
{
  "site_name": string,
  "summary": string,
  "title": string,
  "subtitle": string,
  "cta_text": string,
  "project_type": "static_site" | "fullstack_app",
  "deploy_target": "vercel" | "railway" | "supabase" | "local",
  "auth_required": boolean,
  "use_supabase": boolean,
  "features": [{"title": string, "description": string}],
  "entities": [{"name": string, "columns": [string]}],
  "api_routes": [{"method": string, "path": string, "summary": string}],
  "primary_color": string,
  "gradient_start": string,
  "gradient_end": string
}

Guidelines:
- Prefer "fullstack_app" when the request implies auth, database, dashboards, portals, or APIs.
- Keep features concise and user-facing.
- Include 2-4 entities and 3-5 API routes for fullstack apps.
- Keep color values as hex strings.
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": (
                    f"Prompt: {prompt}\n"
                    f"Preferred project_type: {project_type}\n"
                    f"Preferred deploy_target: {deploy_target}"
                ),
            },
        ],
        temperature=0.4,
        max_tokens=1400,
    )
    content = response.choices[0].message.content or ""
    content = re.sub(r"^```json\s*", "", content.strip())
    content = re.sub(r"\s*```$", "", content)
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        return _fallback_blueprint(prompt, project_type, deploy_target)
