from __future__ import annotations

import json
from pathlib import Path

from wb_models import ProjectSpec


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _write_json(path: Path, content: dict) -> None:
    _write_text(path, json.dumps(content, indent=2) + "\n")


def _render_static_html(spec: ProjectSpec) -> str:
    features = "\n".join(
        (
            "                <div class=\"feature-card\">\n"
            f"                    <h3>{feature.title}</h3>\n"
            f"                    <p>{feature.description}</p>\n"
            "                </div>"
        )
        for feature in spec.features[:3]
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{spec.site_name}</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header class="hero">
        <div class="container">
            <p class="eyebrow">Shipstack generated</p>
            <h1 class="hero-title">{spec.title}</h1>
            <p class="hero-subtitle">{spec.subtitle}</p>
            <a href="#contact" class="btn">{spec.cta_text}</a>
        </div>
    </header>

    <section id="features" class="features">
        <div class="container">
            <h2 class="section-title">What this project includes</h2>
            <div class="feature-grid">
{features}
            </div>
        </div>
    </section>

    <section id="contact" class="contact">
        <div class="container">
            <h2 class="section-title">Next steps</h2>
            <p>{spec.summary}</p>
            <form class="contact-form">
                <input type="text" placeholder="Your Name" required>
                <input type="email" placeholder="Your Email" required>
                <textarea placeholder="What should we change next?" rows="5" required></textarea>
                <button type="submit" class="btn">Send Message</button>
            </form>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2026 {spec.site_name}. Generated by Shipstack.</p>
        </div>
    </footer>
    <script src="script.js"></script>
</body>
</html>
"""


def _render_static_css(spec: ProjectSpec) -> str:
    return f""":root {{
    --primary-color: {spec.primary_color};
    --text-color: #0f172a;
    --bg-color: #f8fafc;
    --card-bg: #ffffff;
}}

* {{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}}

body {{
    font-family: Arial, sans-serif;
    color: var(--text-color);
    background: var(--bg-color);
    line-height: 1.6;
}}

.container {{
    max-width: 1100px;
    margin: 0 auto;
    padding: 0 24px;
}}

.hero {{
    min-height: 60vh;
    display: flex;
    align-items: center;
    text-align: center;
    color: #fff;
    padding: 120px 0;
    background: linear-gradient(135deg, {spec.gradient_start}, {spec.gradient_end});
}}

.eyebrow {{
    text-transform: uppercase;
    letter-spacing: 0.2em;
    font-size: 0.85rem;
    margin-bottom: 16px;
}}

.hero-title {{
    font-size: 3.25rem;
    margin-bottom: 20px;
}}

.hero-subtitle {{
    max-width: 720px;
    margin: 0 auto 32px;
    font-size: 1.15rem;
}}

.btn {{
    display: inline-block;
    padding: 14px 28px;
    border-radius: 999px;
    border: none;
    text-decoration: none;
    background: var(--primary-color);
    color: #fff;
    cursor: pointer;
    font-weight: 600;
}}

.features,
.contact {{
    padding: 80px 0;
}}

.section-title {{
    font-size: 2rem;
    text-align: center;
    margin-bottom: 40px;
}}

.feature-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 24px;
}}

.feature-card {{
    background: var(--card-bg);
    border-radius: 18px;
    padding: 28px;
    box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08);
}}

.contact {{
    background: #fff;
}}

.contact-form {{
    max-width: 560px;
    margin: 24px auto 0;
    display: flex;
    flex-direction: column;
    gap: 16px;
}}

.contact-form input,
.contact-form textarea {{
    width: 100%;
    padding: 14px 16px;
    border-radius: 12px;
    border: 1px solid #dbe2ea;
}}

footer {{
    background: #0f172a;
    color: #fff;
    text-align: center;
    padding: 32px 0;
}}

@media (max-width: 768px) {{
    .hero-title {{
        font-size: 2.4rem;
    }}
}}
"""


def _render_static_js() -> str:
    return """document.querySelector('.contact-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const button = event.currentTarget.querySelector('button');
    if (!button) {
        return;
    }
    const originalLabel = button.textContent;
    button.textContent = 'Message Sent';
    setTimeout(() => {
        button.textContent = originalLabel;
    }, 2500);
    event.currentTarget.reset();
});
"""


def _render_fullstack_package_json(spec: ProjectSpec) -> dict:
    return {
        "name": spec.slug,
        "private": True,
        "version": "0.1.0",
        "type": "module",
        "scripts": {
            "dev": "node server.js",
            "start": "node server.js",
        },
        "dependencies": {
            "@supabase/supabase-js": "^2.49.1",
            "cors": "^2.8.5",
            "dotenv": "^17.3.1",
            "express": "^4.21.2",
        },
    }


def _render_fullstack_server(spec: ProjectSpec) -> str:
    routes = "\n".join(
        (
            f"app.{route.method.lower()}('{route.path}', async (_req, res) => {{\n"
            f"  res.json({{ ok: true, route: '{route.path}', summary: '{route.summary}' }});\n"
            "});"
        )
        for route in spec.api_routes
        if route.path != "/api/health"
    )
    return f"""import cors from 'cors';
import dotenv from 'dotenv';
import express from 'express';
import path from 'node:path';
import {{ fileURLToPath }} from 'node:url';
import {{ createClient }} from '@supabase/supabase-js';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const port = Number(process.env.PORT || 3000);
const publicDir = path.join(__dirname, 'public');

const supabaseUrl = process.env.SUPABASE_URL || '';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const supabase = supabaseUrl && supabaseAnonKey
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

app.use(cors());
app.use(express.json());
app.use(express.static(publicDir));

app.get('/api/health', (_req, res) => {{
  res.json({{
    ok: true,
    app: '{spec.site_name}',
    authRequired: {str(spec.auth_required).lower()},
    supabaseEnabled: Boolean(supabase),
  }});
}});

app.get('/api/config', (_req, res) => {{
  res.json({{
    siteName: '{spec.site_name}',
    summary: {json.dumps(spec.summary)},
    authRequired: {str(spec.auth_required).lower()},
    entities: {json.dumps([entity.name for entity in spec.entities])},
  }});
}});

{routes}

app.get('*', (_req, res) => {{
  res.sendFile(path.join(publicDir, 'index.html'));
}});

app.listen(port, () => {{
  console.log(`{spec.site_name} listening on ${{port}}`);
}});
"""


def _render_fullstack_html(spec: ProjectSpec) -> str:
    feature_items = "\n".join(
        f"<li><strong>{feature.title}</strong>: {feature.description}</li>" for feature in spec.features
    )
    entity_rows = "\n".join(
        f"<li><code>{entity.name}</code> - {', '.join(entity.columns)}</li>" for entity in spec.entities
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{spec.site_name}</title>
  <link rel="stylesheet" href="/styles.css">
</head>
<body>
  <header class="hero">
    <div class="container">
      <p class="eyebrow">Full-stack Shipstack app</p>
      <h1>{spec.title}</h1>
      <p>{spec.subtitle}</p>
      <button id="refreshButton" class="btn">{spec.cta_text}</button>
    </div>
  </header>

  <main class="container">
    <section class="panel">
      <h2>Overview</h2>
      <p>{spec.summary}</p>
      <ul>{feature_items}</ul>
    </section>

    <section class="panel">
      <h2>Data model</h2>
      <ul>{entity_rows}</ul>
    </section>

    <section class="panel">
      <h2>Runtime status</h2>
      <pre id="status">Loading...</pre>
    </section>
  </main>

  <script src="/app.js"></script>
</body>
</html>
"""


def _render_fullstack_css(spec: ProjectSpec) -> str:
    return f""":root {{
  --primary-color: {spec.primary_color};
  --gradient-start: {spec.gradient_start};
  --gradient-end: {spec.gradient_end};
  --surface: #ffffff;
  --background: #f8fafc;
  --text: #0f172a;
}}

* {{
  box-sizing: border-box;
}}

body {{
  margin: 0;
  font-family: Arial, sans-serif;
  background: var(--background);
  color: var(--text);
}}

.container {{
  width: min(1100px, calc(100% - 32px));
  margin: 0 auto;
}}

.hero {{
  padding: 96px 0 72px;
  background: linear-gradient(135deg, var(--gradient-start), var(--gradient-end));
  color: #fff;
}}

.eyebrow {{
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 0.8rem;
}}

.btn {{
  margin-top: 16px;
  padding: 12px 24px;
  background: var(--primary-color);
  color: #fff;
  border: none;
  border-radius: 999px;
  cursor: pointer;
}}

main {{
  padding: 40px 0 80px;
  display: grid;
  gap: 24px;
}}

.panel {{
  background: var(--surface);
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 12px 30px rgba(15, 23, 42, 0.08);
}}

pre {{
  white-space: pre-wrap;
  background: #0f172a;
  color: #e2e8f0;
  padding: 16px;
  border-radius: 12px;
}}
"""


def _render_fullstack_js() -> str:
    return """async function refreshStatus() {
  const status = document.getElementById('status');
  try {
    const [healthResponse, configResponse] = await Promise.all([
      fetch('/api/health'),
      fetch('/api/config'),
    ]);
    const health = await healthResponse.json();
    const config = await configResponse.json();
    status.textContent = JSON.stringify({ health, config }, null, 2);
  } catch (error) {
    status.textContent = `Failed to load runtime status: ${error}`;
  }
}

document.getElementById('refreshButton')?.addEventListener('click', refreshStatus);
refreshStatus();
"""


def _render_env_example(spec: ProjectSpec) -> str:
    return f"""APP_NAME={spec.slug}
PORT=3000
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_PROJECT_REF=
SUPABASE_DB_PASSWORD=
"""


def _render_dockerfile() -> str:
    return """FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
"""


def _render_dockerignore() -> str:
    return """node_modules
npm-debug.log
.env
"""


def _render_project_readme(spec: ProjectSpec) -> str:
    return f"""# {spec.site_name}

Generated by Shipstack.

## Summary

{spec.summary}

## Project Type

- `{spec.project_type}`
- Deploy target: `{spec.deploy_target}`
- Supabase enabled: `{str(spec.use_supabase).lower()}`

## Local Development

```bash
npm install
npm run dev
```

## Generated API Routes

{chr(10).join(f"- `{route.method} {route.path}` - {route.summary}" for route in spec.api_routes)}
"""


def _render_shipstack_manifest(spec: ProjectSpec) -> dict:
    return {
        "site_name": spec.site_name,
        "project_type": spec.project_type,
        "deploy_target": spec.deploy_target,
        "auth_required": spec.auth_required,
        "use_supabase": spec.use_supabase,
        "features": [feature.__dict__ for feature in spec.features],
        "entities": [entity.__dict__ for entity in spec.entities],
        "api_routes": [route.__dict__ for route in spec.api_routes],
    }


def _render_migration_sql(spec: ProjectSpec) -> str:
    statements: list[str] = []
    for entity in spec.entities:
        columns = entity.columns or ["id uuid primary key", "name text", "created_at timestamptz default now()"]
        statement = ",\n  ".join(columns)
        statements.append(f"create table if not exists {entity.name} (\n  {statement}\n);")
    return "\n\n".join(statements) + "\n"


def scaffold_project(spec: ProjectSpec, project_path: Path) -> dict[str, str]:
    files: dict[str, str] = {}

    _write_json(project_path / "shipstack.project.json", _render_shipstack_manifest(spec))
    files["manifest"] = str(project_path / "shipstack.project.json")

    if spec.project_type == "static_site":
        _write_text(project_path / "index.html", _render_static_html(spec))
        _write_text(project_path / "styles.css", _render_static_css(spec))
        _write_text(project_path / "script.js", _render_static_js())
        _write_json(project_path / "vercel.json", {"version": 2, "public": True})
        files["entrypoint"] = str(project_path / "index.html")
    else:
        _write_json(project_path / "package.json", _render_fullstack_package_json(spec))
        _write_text(project_path / "server.js", _render_fullstack_server(spec))
        _write_text(project_path / "public" / "index.html", _render_fullstack_html(spec))
        _write_text(project_path / "public" / "styles.css", _render_fullstack_css(spec))
        _write_text(project_path / "public" / "app.js", _render_fullstack_js())
        _write_text(project_path / ".env.example", _render_env_example(spec))
        _write_text(project_path / "Dockerfile", _render_dockerfile())
        _write_text(project_path / ".dockerignore", _render_dockerignore())
        _write_json(
            project_path / "railway.json",
            {
                "$schema": "https://railway.com/railway.schema.json",
                "build": {"builder": "DOCKERFILE", "dockerfilePath": "Dockerfile"},
                "deploy": {"startCommand": "npm start", "restartPolicyType": "ON_FAILURE"},
            },
        )
        _write_text(project_path / "README.md", _render_project_readme(spec))
        files["entrypoint"] = str(project_path / "server.js")

    if spec.use_supabase:
        _write_text(project_path / "supabase" / "config.toml", '[project]\nname = "shipstack-generated"\n')
        _write_text(
            project_path / "supabase" / "migrations" / "20260315000000_initial.sql",
            _render_migration_sql(spec),
        )
        files["supabase"] = str(project_path / "supabase")

    return files
